[build]
  publish = "public"
  command = "echo 'No build required'"

# 모든 요청을 pinet.com으로 프록시
[[redirects]]
  from = "/proxy/*"
  to = "https://meverse8856.pinet.com/:splat"
  status = 200
  force = true
