[build]
  publish = "public"
  command = "echo 'No build required'"

# 접속 시 me2verse-1.netlify.app으로 이동
[[redirects]]
  from = "/*"
  to = "https://me2verse-1.netlify.app"
  status = 301
  force = true
