name: glTF Optimize & Upload
on:
  push:
    paths:
      - 'assets/**'
jobs:
  optimize-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install gltf-transform
        run: |
          npm i -g @gltf-transform/cli @gltf-transform/extensions
      - name: Optimize GLB
        run: |
          mkdir -p out
          for f in assets/*.glb; do
            name=$(basename "$f")
            gltf-transform copy "$f" "out/$name" --prune
            gltf-transform draco "out/$name" -s 10 -o "out/$name"
            gltf-transform ktx2 "out/$name" -o "out/$name" --q 80
          done
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.6.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
